on:
  workflow_call:
    inputs:
      imageName:
        required: false
        type: string
        default: "ghcr.io/markjgardner/taintremover:0.4.${{ github.run_number }}"
      runner:
        required: true
        type: string
      registry:
        required: false
        type: string
        default: ghcr.io
      baseTag:
        required: true
        type: string
    outputs:
      fullImageName:
        description: "The fully qualified name of the built image"
        value: ${{ jobs.build-image.outputs.imageName }}
jobs:
  build-image:
    runs-on: ${{ inputs.runner }}
    defaults:
      run:
        working-directory: ./src
    env:
      FULL_IMAGE_NAME: "${{ inputs.imageName }}-${{ inputs.baseTag }}"
    outputs:
      imageName: ${{ steps.setOutput.outputs.imageName }}
    steps:
      - uses: actions/checkout@v2
      
      - id: setOutput
        run: echo "::set-output name=imageName::${{ env.FULL_IMAGE_NAME }}"

      - name: Build Linux Image
        run: docker build -t "${{ env.FULL_IMAGE_NAME }}" --build-arg BASE_TAG=${{ inputs.baseTag }} .
      
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to registry
        run: docker push ${{ env.FULL_IMAGE_NAME }}
